In [109]:
pip install selenium

Requirement already satisfied: selenium in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (4.30.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from selenium) (2.3.0)
Requirement already satisfied: trio~=0.17 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from selenium) (0.29.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from selenium) (2025.1.31)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from selenium) (4.13.0)
Requirement already satisfied: websocket-client~=1.8 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (3.10)
Requirement already satisfied: outcome in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (1.17.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.22)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [110]:
pip install pandas

Requirement already satisfied: pandas in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\felip\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\felip\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\felip\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [111]:
import pandas as pd

In [112]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By

In [ ]:
service = Service()

options = webdriver.ChromeOptions()

driver = webdriver.Chrome(service=service, options=options)

In [143]:
url = "https://books.toscrape.com"

driver.get(url)

In [144]:
driver.find_elements(By.TAG_NAME, "a")[54].get_attribute("title")

'A Light in the Attic'

In [154]:
titleElements = driver.find_elements(By.TAG_NAME, "a")[54:94:2]

In [146]:
titleList = [title.get_attribute("title") for title in titleElements]

In [ ]:
titleElements = driver.find_elements(By.TAG_NAME, "a")[54:94:2]

titleElements[0].click()

In [148]:
driver.back()

In [149]:
int(driver.find_element(By.CLASS_NAME, "instock").text.replace('In stock (', "").replace(' available)', ""))

22

In [133]:
titlelist = driver.find_elements(By.TAG_NAME, "a")[54:94:2]
stocklist = []

for title in titleElements:
    title.click()

    qtdstock = int(driver.find_element(By.CLASS_NAME, "instock").text.replace('In stock (', "").replace(' available)', ""))

    stocklist.append(qtdstock)

    driver.back()

In [ ]:
stocklist

[22,
 20,
 20,
 20,
 20,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19]

In [151]:
dictDF = {"Title": titleList,
          "Stock": stocklist}

pd.DataFrame(dictDF)

                                                Title  Stock
0                                A Light in the Attic     22
1                                  Tipping the Velvet     20
2                                          Soumission     20
3                                       Sharp Objects     20
4               Sapiens: A Brief History of Humankind     20
5                                     The Requiem Red     19
6   The Dirty Little Secrets of Getting Your Dream...     19
7   The Coming Woman: A Novel Based on the Life of...     19
8   The Boys in the Boat: Nine Americans and Their...     19
9                                     The Black Maria     19
10     Starving Hearts (Triangular Trade Trilogy, #1)     19
11                              Shakespeare's Sonnets     19
12                                        Set Me Free     19
13  Scott Pilgrim's Precious Little Life (Scott Pi...     19
14                          Rip it Up and Start Again     19
15  Our Band Could Be Your Life: Scenes from the A...     19
16                                               Olio     19
17  Mesaerion: The Best Science Fiction Stories 18...     19
18                       Libertarianism for Beginners     19
19                            It's Only the Himalayas     19

In [162]:
dictDF = {"Title": titleList}

pd.DataFrame(dictDF)

                                                Title
0                                A Light in the Attic
1                                  Tipping the Velvet
2                                          Soumission
3                                       Sharp Objects
4               Sapiens: A Brief History of Humankind
5                                     The Requiem Red
6   The Dirty Little Secrets of Getting Your Dream...
7   The Coming Woman: A Novel Based on the Life of...
8   The Boys in the Boat: Nine Americans and Their...
9                                     The Black Maria
10     Starving Hearts (Triangular Trade Trilogy, #1)
11                              Shakespeare's Sonnets
12                                        Set Me Free
13  Scott Pilgrim's Precious Little Life (Scott Pi...
14                          Rip it Up and Start Again
15  Our Band Could Be Your Life: Scenes from the A...
16                                               Olio
17  Mesaerion: The Best Science Fiction Stories 18...
18                       Libertarianism for Beginners
19                            It's Only the Himalayas